spring:
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html

  application:
    name: tmall-demo

#  datasource:
#    url: jdbc:mysql://192.168.177.128:3306/mymall?useUnicode=true&characterEncoding=utf-8&verifyServerCertificate=false&useSSL=false&requireSSL=false
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: kobe111


  datasource:
    url: jdbc:mysql://192.168.177.128:3306/mymall?useUnicode=true&characterEncoding=utf-8&verifyServerCertificate=false&useSSL=false&requireSSL=false&serverTimeZone=GMT
    username: root
    password: kobe111
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 2
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
      validation-query: select 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  profiles:
    active: dev

  devtools:
    restart:
      enabled: true
      exclude: WEB-INF/**

  redis:
    database: 0
    host: 192.168.177.128
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    port: 6379
    timeout: 15000

logging:
  file:
    path: d:/log/tmall
#    name: ${spring.application.name}.log
  level:
    com : info
    org.springframework.web: "info"



# ===== 自定义swagger配置 ===== #
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: tech-demo
#  try-host: http://localhost:${server.port}

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-portal-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

server:
  port: 9090





person:
  name: txb
  age: 25
  company: 比地


