spring:
  thymeleaf:
    cache: false
#    prefix: classpath:/templates/
    mode: HTML #设置模板类型
    encoding: utf-8  #设置编码
  mvc:
    view:
      suffix: .html
    # 应该以什么样的路径来访问静态资源,粗暴放开swagger
#    static-path-pattern: /static/**
    static-path-pattern: /*/**


  application:
    name: tmall-protal

  datasource:
    url: jdbc:mysql://192.168.244.129:3306/demo?serverTimezone=UTC
#    url: jdbc:mysql://192.168.177.128:3306/mymall
#    url: jdbc:mysql://121.36.75.169:3306/mymall
    username: root
#    password: Kobe111!
#    password: kobe111
    password: kobe>1@R
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 2
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
      validation-query: select 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  redis:
#    host: localhost
    host: 192.168.177.128
#    host: 121.36.75.169 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
#    password: kobe111
    timeout: 3000ms # 连接超时时间（毫秒）

  #热加载
  devtools:
#    additional-paths: static/**,templates/**
    restart:
      enabled: true
      exclude: WEB-INF/**
#    livereload:
#      enabled: true

  #cloud-nacos
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


  rabbitmq:
    host: localhost # rabbitmq的连接地址
    port: 5672 # rabbitmq的连接端口号
    virtual-host: tmall # rabbitmq的虚拟host
    username: tmall # rabbitmq的用户名
    password: tmall # rabbitmq的密码
    connection-timeout: 5000

logging:
  file:
    path: d:/logs/
    name: ${spring.application.name}.log
  level:
    com : info

server:
  port: 8080
#  servlet:
#    context-path: /${spring.application.name}


mybatis:
  mapper-locations:
    - classpath:mappers/**/*.xml
#    - classpath*:com/**/mappers/*.xml

pagehelper:
  helperDialect: mysql
  params: count=countSql
  reasonable: true
  supportMethodsArguments: true




# ===== 自定义配置 ===== #

swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: spring-security-integration
#  try-host: http://localhost:${server.port}

myRedis:
  flashsaleMonitorKey: flashsaleMonitorKey
  flashsaleIncrKey: flashsaleIncrKey
  orderTimeout: 600000
  toPay: toPay
  orderListPrefix: orderList
  toPayOrderLockPrefix: toPayOrderLock

#security白名单
secure:
  ignored:
    urls:
      - /swagger-ui.html
      - /doc.html
      - /swagger-ui/*
      - /swagger-resources/**
      - /v2/api-docs
      - /v3/api-docs
      - /webjars/**
      - /static/css/**
      - /static/fonts/**
      - /static/image/**
      - /static/js/**
      - /static/mycss/**
      - /static/myjs/**


service-url:
  nacos-order-server: http://tmall-cloud-order