spring:
  thymeleaf:
    cache: false
  mvc:
    view:
      suffix: .html
  application:
    name: tmall-protal
  datasource:
    url: jdbc:mysql://121.36.75.169:3306/tmall
    username: root
    password: Kobe111!
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 2
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
      validation-query: select 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000


logging:
  file:
    path: /logs/
    name: ${spring.application.name}.log
  level:
    com : debug



# ===== 自定义swagger配置 ===== #
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: spring-security-integration
#  try-host: http://localhost:${server.port}



server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}


mybatis:
  mapper-locations:
    - classpath:mappers/**/*.xml
#    - classpath*:com/**/mappers/*.xml

pagehelper:
  helperDialect: mysql
  params: count=countSql
  reasonable: true
  supportMethodsArguments: true


