spring:
  thymeleaf:
    cache: false
  mvc:
    view:
      suffix: .html
  application:
    name: tmall-protal


logging:
  file:
    path: /logs/
    name: ${spring.application.name}.log
  level:
    com : debug



# ===== 自定义swagger配置 ===== #
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: spring-security-integration
#  try-host: http://localhost:${server.port}



server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}


mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
