server:
  port: 8083
spring:
  application:
    name: tmall-cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    #网关配置
    gateway:
      routes:
        - id: create-order1
          uri: lb://tmall-cloud-order
          predicates:
            - Path=/order/createOrder/**
            - After=2021-03-11T11:26:47.897+08:00[Asia/Shanghai]
            #between before prormapping
#      discovery:
#        locator:
#          enabled: true












  #热加载
  devtools:
    #    additional-paths: static/**,templates/**
    restart:
      enabled: true
      exclude: WEB-INF/**
#    livereload:
#      enabled: true



