server:
  port: 8081
spring:
  application:
    name: tmall-cloud-order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  #热加载
  devtools:
    #    additional-paths: static/**,templates/**
    restart:
      enabled: true
      exclude: WEB-INF/**
#    livereload:
#      enabled: true